apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeus-frontend.fullname" . }}
  labels:
    {{- include "zeus-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "zeus-frontend.selectorLabels" . | nindent 4 }}
